club_name: Sheffield University Rugby Football Club
address: Western Bank, Sheffield S10 2TN
email: email@sheffield.felixmakeitnow
join_url: https://su.sheffield.ac.uk/shop
bucs_url: https://bucs.playwaze.com/bucs-rugby-union-25-26/xva3fcfo6cdxb/league-display/Leagues/ni9tntcgkhh9q2
facebook: https://www.facebook.com/SURFCofficial/
instagram: https://www.instagram.com/sheffieldurfc/
tiktok: https://www.tiktok.com/@sheffieldurfc
